tar xvf tarball/build.bin
tar xvf tarball/x86_64-linux-gnu.a.bin
tar xvf tarball/x86_64-linux-gnu.b.bin
tar xvf tarball/x86_64-linux-gnu.c.bin
tar xvf tarball/x86_64-linux-gnu.d.bin
tar xvf tarball/x86_64-linux-gnu.e.bin
tar xvf tarball/x86_64-linux-gnu.f.bin
tar xvf tarball/x86_64-linux-gnu.g.bin
tar xvf tarball/x86_64-linux-gnu.h.bin
tar xvf tarball/x86_64-linux-gnu.i.bin
tar xvf tarball/x86_64-linux-gnu.j.bin
tar xvf tarball/x86_64-linux-gnu.k.bin
tar xvf tarball/x86_64-linux-gnu.l.bin
tar xvf tarball/x86_64-linux-gnu.m.bin
tar xvf tarball/x86_64-linux-gnu.n.bin
tar xvf tarball/x86_64-linux-gnu.o.bin
tar xvf tarball/x86_64-linux-gnu.p.bin
tar xvf tarball/x86_64-linux-gnu.r.bin
tar xvf tarball/x86_64-linux-gnu.s.bin
tar xvf tarball/x86_64-linux-gnu.t.bin
tar xvf tarball/x86_64-linux-gnu.u.bin
tar xvf tarball/x86_64-linux-gnu.v.bin
tar xvf tarball/x86_64-linux-gnu.x.bin
tar xvf tarball/x86_64-linux-gnu.z.bin
